spring:
  application:
    name: matrix-backend
  profiles:
    active: dev

server:
  port: 8080

# SpringDoc / OpenAPI 配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
